# docker-compose.yml
version: "3.8"

services:
  portfolio:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: unless-stopped
