# docker-compose.yml
version: "3.8"

services:
  portfolio:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "8888:8888"
    restart: unless-stopped

  # Servicio de desarrollo
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8080
    profiles:
      - dev
