# Dockerfile.dev
FROM oven/bun:1-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./
COPY bun.lockb ./

# Instalar dependencias
RUN bun install --frozen-lockfile

# Copiar código fuente
COPY . .

# Exponer puerto de desarrollo
EXPOSE 4321

CMD ["bun", "run", "dev", "--host"]